-- Migration V21: Add Enterprise Fields to Shops
-- Generated by Mbeck Agent for Phase 5 (Enterprise)
-- Target: Supabase (PostgreSQL)

-- 1. Add Owner and Chain columns
ALTER TABLE public.shops 
ADD COLUMN IF NOT EXISTS owner_id UUID REFERENCES auth.users(id),
ADD COLUMN IF NOT EXISTS chain_id UUID; -- Can reference a 'chains' table in future

-- 2. Index for Performance
CREATE INDEX IF NOT EXISTS idx_shops_owner ON public.shops(owner_id);

-- 3. Row Level Security for Shops
ALTER TABLE public.shops ENABLE ROW LEVEL SECURITY;

-- Policy: Owners can VIEW their own shops
CREATE POLICY "Owners can view their shops" 
ON public.shops FOR SELECT 
USING (auth.uid() = owner_id);

-- Policy: Owners can UPDATE their own shops
CREATE POLICY "Owners can update their shops" 
ON public.shops FOR UPDATE 
USING (auth.uid() = owner_id);

-- Policy: Owners can INSERT new shops (Opening a new branch)
CREATE POLICY "Owners can create shops" 
ON public.shops FOR INSERT 
WITH CHECK (auth.uid() = owner_id);
