-- Migration V24: Search Logs (The Feedback Loop)
-- Generated by Mbeck Agent
-- Target: Supabase (PostgreSQL)

CREATE TABLE IF NOT EXISTS public.search_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_text TEXT NOT NULL,
    results_count INTEGER DEFAULT 0,
    
    -- Analytics
    device_id TEXT, -- Anonymous tracking
    location_lat FLOAT,
    location_lng FLOAT,
    
    -- Timestamp
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for Analytics
CREATE INDEX IF NOT EXISTS idx_search_logs_query ON public.search_logs(query_text);
CREATE INDEX IF NOT EXISTS idx_search_logs_created ON public.search_logs(created_at);

-- Security:
-- Buyers (Anon) can INSERT logs (via Edge Function or direct if allowed).
-- Sellers (Auth) can READ logs (Aggregated).

-- For simplicity in Phase 3, we allow Public Insert but No Read.
ALTER TABLE public.search_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can log searches" 
ON public.search_logs FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- Only Admins/System can read raw logs (Privacy).
-- Sellers will see Aggregates later via View/Function.
