-- Migration V20: Create Cloud Inventory Table
-- Generated by Mbeck Agent to fix "Schema Drift"
-- Target: Supabase (PostgreSQL)

-- 1. Enable UUID extension if needed (good practice for Cloud IDs, but local uses Integer)
-- We will keep Integer IDs for V1 sync relying on "Server ID" mapping later, 
-- or use the same ID if we trust the single-device origin.
-- For standard sync, Cloud usually has its own UUID PK and a separate 'local_id' column.
-- However, to match the current 'Drift' check, we will mirror the local schema exactly first.

CREATE TABLE IF NOT EXISTS public.inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Maps to local INTEGER AUTOINCREMENT
    name TEXT NOT NULL,
    category TEXT,
    "sellingPrice" FLOAT, -- Quoted to preserve camelCase if preferred, or use snake_case map
    "originalPrice" FLOAT,
    stock INTEGER DEFAULT 0,
    "imagePath" TEXT, -- Note: Cloud might store URL here instead of path
    visual_vector TEXT, -- Stored as JSON string or Raw Text
    specification TEXT,
    barcode TEXT,
    
    -- Sync Metadata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    shop_id UUID DEFAULT auth.uid() -- RLS Tenant Isolation
);

-- 2. Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_inventory_name ON public.inventory(name);
CREATE INDEX IF NOT EXISTS idx_inventory_barcode ON public.inventory(barcode);

-- 3. Row Level Security (RLS)
-- Crucial for Multi-Tenant Security (Phase 2)
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;

-- Policy: Owners can see their own items
CREATE POLICY "Users can all inventory of their shop" 
ON public.inventory FOR ALL 
USING (auth.uid() = shop_id);
