-- Migration V27: Demand Analytics View
-- Generated by Mbeck Agent
-- Target: Supabase (PostgreSQL)

-- 1. Create View for Unmet Demand (Missed Revenue)
-- Aggregates searches that returned 0 results in the last 7 days.
CREATE OR REPLACE VIEW public.analytics_demand_unmet AS
SELECT 
    query_text,
    COUNT(*) as demand_count,
    MAX(created_at) as last_seen_at
FROM 
    public.search_logs
WHERE 
    results_count = 0
    AND created_at > (NOW() - INTERVAL '7 days')
GROUP BY 
    query_text
ORDER BY 
    demand_count DESC;

-- 2. Grant Access
-- Allow Authenticated Users (Sellers) to read this view.
GRANT SELECT ON public.analytics_demand_unmet TO authenticated;

-- Note: In Phase 2 (Geo), we will add filtered views based on ST_Distance.
-- For now, this is Global Demand (good enough for initial pilot).
