-- Migration V26 (Revised 3): Fix Inventory ID Type, Policy, Clean Data & FK
-- Generated by Mbeck Agent to resolve UUID vs TEXT conflict
-- Target: Supabase (PostgreSQL)

-- 1. Drop Dependencies (Policy)
DROP POLICY IF EXISTS "Users can all inventory of their shop" ON public.inventory;

-- 2. Change shop_id from UUID to TEXT
ALTER TABLE public.inventory
ALTER COLUMN shop_id TYPE TEXT USING shop_id::text;

ALTER TABLE public.inventory
ALTER COLUMN shop_id SET DEFAULT auth.uid()::text;

-- 3. CLEANUP: Delete Orphaned Inventory
-- Remove items that reference a Shop ID that doesn't exist.
-- Essential because we are adding a strict FK constraint.
DELETE FROM public.inventory 
WHERE shop_id NOT IN (SELECT id FROM public.shops);

-- 4. Re-create Policy (With Type Cast)
CREATE POLICY "Users can all inventory of their shop" 
ON public.inventory FOR ALL 
USING (auth.uid()::text = shop_id);

-- 5. Add Foreign Key Constraint
ALTER TABLE public.inventory
ADD CONSTRAINT fk_inventory_shop
FOREIGN KEY (shop_id) 
REFERENCES public.shops(id)
ON DELETE CASCADE;

-- 6. Reload Schema
NOTIFY pgrst, 'reload config';
