-- Migration V25: Public Trust Score
-- Generated by Mbeck Agent
-- Target: Supabase (PostgreSQL)

-- 1. Add Trust Columns to Shops
ALTER TABLE public.shops 
ADD COLUMN IF NOT EXISTS trust_score INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS tier TEXT DEFAULT 'NEW';

-- 2. Make them visible to Public (Already done in V22, but ensuring here)
-- Policy "Public can view shops" exists and selects (true) aka all columns.
-- If we wanted to restrict seeing 'password_hash', we should have used a view.
-- For now, this exposes 'trust_score' automatically.

-- 3. Index for filtering "High Trust Shops"
CREATE INDEX IF NOT EXISTS idx_shops_trust ON public.shops(trust_score DESC);
