-- Migration V31: Enterprise Hierarchy (Phase 2) - ROBUST FIX
-- Generated by Antigravity Agent
-- Purpose: Enable Multi-Tenant features (Franchises, Chains, Employee Roles)
-- Fixes: "text = uuid" errors and explicitly handles mixed types during migration.

-- 1. Create Franchises Table (Top Level Organization)
CREATE TABLE IF NOT EXISTS public.franchises (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    owner_id UUID REFERENCES auth.users(id)
);

-- 2. Update Shops Table (Physical Locations)
-- Ensure shops has the necessary enterprise columns
ALTER TABLE public.shops 
ADD COLUMN IF NOT EXISTS region TEXT,
ADD COLUMN IF NOT EXISTS franchise_id TEXT REFERENCES public.franchises(id),
ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'KES';

-- Add owner_id if missing. Use DO block to handle complex dependency checks if needed, 
-- but IF NOT EXISTS is usually sufficient for columns.
ALTER TABLE public.shops ADD COLUMN IF NOT EXISTS owner_id UUID REFERENCES auth.users(id);

-- Also add 'name' if the existing table used 'business_name' (alignment)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'shops' AND column_name = 'business_name') 
  AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'shops' AND column_name = 'name') THEN
    ALTER TABLE public.shops RENAME COLUMN business_name TO name;
  END IF;
END $$;

-- 3. Create Shop Members (Store-Level Access)
-- Mapping Devices/Users to Shops with specific roles
CREATE TYPE public.shop_role AS ENUM ('owner', 'manager', 'clerk');

CREATE TABLE IF NOT EXISTS public.shop_members (
    shop_id TEXT REFERENCES public.shops(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    role public.shop_role NOT NULL DEFAULT 'clerk',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (shop_id, user_id)
);

-- 4. Create Franchise Members (HQ-Level Access)
-- Mapping Users to Franchises
CREATE TYPE public.franchise_role AS ENUM ('super_admin', 'regional_manager');

CREATE TABLE IF NOT EXISTS public.franchise_members (
    franchise_id TEXT REFERENCES public.franchises(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    role public.franchise_role NOT NULL DEFAULT 'regional_manager',
    region_access TEXT, -- If null, access all. If set, restricts to shops.region
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (franchise_id, user_id)
);

-- 5. Enable RLS on New Tables
ALTER TABLE public.franchises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shop_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.franchise_members ENABLE ROW LEVEL SECURITY;

-- 6. Define Policies (The "Brain" of Phase 2)

-- Clean up old policies to avoid conflicts
DROP POLICY IF EXISTS "Users can view their own shop memberships" ON public.shop_members;
DROP POLICY IF EXISTS "Members can view their assigned shops" ON public.shops;
DROP POLICY IF EXISTS "Enterprise Inventory Access" ON public.inventory;

-- A. Shop Members can view their own membership
CREATE POLICY "Users can view their own shop memberships"
    ON public.shop_members FOR SELECT
    USING (auth.uid() = user_id);

-- B. Shop Members can view the Shops they belong to
CREATE POLICY "Members can view their assigned shops"
    ON public.shops FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.shop_members sm 
            WHERE sm.shop_id::text = shops.id::text -- CAST BOTH SIDES
            AND sm.user_id = auth.uid()
        )
    );

-- C. Inventory Access Update (The critical change)
-- We cast everything to TEXT to handle `shop_id` being UUID in inventory but TEXT in shops/members.

-- Drop old V1 policy if it exists (it was "Users can all inventory of their shop" with auth.uid() = shop_id)
DROP POLICY IF EXISTS "Users can all inventory of their shop" ON public.inventory;

-- Create New Comprehensive Policy
CREATE POLICY "Enterprise Inventory Access"
    ON public.inventory FOR ALL
    USING (
        -- 1. Direct Shop Membership (Works for Independent Owners too if they add themselves as member)
        EXISTS (
            SELECT 1 FROM public.shop_members sm
            WHERE sm.shop_id::text = inventory.shop_id::text -- CAST BOTH SIDES for safety
            AND sm.user_id = auth.uid()
        )
        OR
        -- 2. Franchise Level Access
        EXISTS (
            SELECT 1 FROM public.shops s
            JOIN public.franchise_members fm ON s.franchise_id::text = fm.franchise_id::text
            WHERE s.id::text = inventory.shop_id::text -- CAST BOTH SIDES
            AND fm.user_id = auth.uid()
            AND (
                fm.role = 'super_admin'
                OR
                (fm.role = 'regional_manager' AND (fm.region_access IS NULL OR fm.region_access = s.region))
            )
        )
        OR 
        -- 3. Legacy V1 Support (Direct Owner via shop_id = user_id)
        -- This keeps the app working for current users who haven't migrated to the `shops` table yet.
        (inventory.shop_id::text = auth.uid()::text) -- Cast auth.uid to match inventory
    );

-- 7. Helper Function to "Claim" a shop (Migration Helper)
-- Allows a V1 user to create a real `shops` entry from their user ID.
CREATE OR REPLACE FUNCTION public.migrate_v1_to_shop(shop_name TEXT)
RETURNS TEXT AS $$ -- FIXED: Returns TEXT
DECLARE
    new_shop_id TEXT; -- FIXED: Variable is TEXT
BEGIN
    -- unique shop ID (could use user ID to keep it simple, or generate new)
    -- We'll generate a new one to decouple.
    INSERT INTO public.shops (name, owner_id)
    VALUES (shop_name, auth.uid())
    RETURNING id::text INTO new_shop_id;

    -- Add user as owner/manager
    INSERT INTO public.shop_members (shop_id, user_id, role)
    VALUES (new_shop_id, auth.uid(), 'owner');

    RETURN new_shop_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
