-- Migration V22: Public Access & Shop Contact
-- Generated by Mbeck Agent for Buyer App (Phase 1)
-- Target: Supabase (PostgreSQL)

-- 1. Add Contact Info to Shops (for Buyers to call)
ALTER TABLE public.shops 
ADD COLUMN IF NOT EXISTS contact_phone TEXT;

-- 2. Allow Public to READ Shops (so they can find them)
-- Note: We intentionally expose business_name, contact_phone, id. 
-- We do NOT want to expose password_hash etc, but Postgres policies operate on ROW level usually.
-- Ideally we use a VIEW for strict column security, but for now we trust the client query 
-- combined with the fact that sensitive cols are hashes.
CREATE POLICY "Public can view shops"
ON public.shops FOR SELECT
TO anon, authenticated
USING (true); -- Visible to everyone

-- 3. Allow Public to READ Inventory (Global Search)
CREATE POLICY "Public can view inventory"
ON public.inventory FOR SELECT
TO anon, authenticated
USING (true); -- Visible to everyone
