-- =========================================================
-- MBECK OPTIMIZED SUPABASE SCHEMA
-- Directive: "Heavy Edge, Light Cloud" with Pro/Enterprise Cloud Sync Support
-- =========================================================

-- 1. DEPRECATED / REMOVED TABLES
-- The following tables violate the edge-first architecture and have been designated for removal.
DROP TABLE IF EXISTS public.public_shops CASCADE;
DROP TABLE IF EXISTS public.public_inventory CASCADE;
DROP TABLE IF EXISTS public.public_app_models CASCADE;
DROP TABLE IF EXISTS public.search_logs CASCADE;

-- 2. ENTERPRISE & PRO SYNC TABLES (Kept online for Dashboards)
CREATE TABLE public.restaurant_orders ( 
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(), 
    shop_id text, 
    table_number text, 
    order_type text DEFAULT 'dine_in' CHECK (order_type = ANY (ARRAY['dine_in','takeaway','delivery'])), 
    order_items jsonb DEFAULT '[]'::jsonb, 
    subtotal numeric, 
    tax_amount numeric DEFAULT 0, 
    total_amount numeric, 
    status text DEFAULT 'pending' CHECK (status = ANY (ARRAY['pending','confirmed','preparing','ready','served','paid','cancelled'])), 
    customer_name text, 
    customer_phone text, 
    notes text, 
    created_at timestamptz DEFAULT now() 
);

CREATE TABLE public.services_appointments ( 
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(), 
    shop_id text, 
    service_id uuid, 
    customer_device_id text, 
    customer_name text, 
    customer_phone text, 
    appointment_time timestamptz, 
    status text DEFAULT 'pending' CHECK (status = ANY (ARRAY['pending','confirmed','completed','cancelled','no_show'])), 
    notes text, 
    total_amount numeric, 
    created_at timestamptz DEFAULT now() 
);

CREATE TABLE public.lodging_reservations ( 
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(), 
    shop_id text, 
    local_id integer, 
    room_id uuid, 
    guest_name text, 
    guest_phone text, 
    guest_email text, 
    guest_id_number text, 
    check_in_date timestamptz, 
    check_out_date timestamptz, 
    actual_check_in timestamptz, 
    actual_check_out timestamptz, 
    nights integer DEFAULT 1, 
    rate_per_night numeric DEFAULT 0, 
    extras_total numeric DEFAULT 0, 
    total_amount numeric DEFAULT 0, 
    amount_paid numeric DEFAULT 0, 
    status text DEFAULT 'pending' CHECK (status = ANY (ARRAY['pending','confirmed','checked_in','checked_out','cancelled'])), 
    notes text, 
    created_at timestamptz DEFAULT now(), 
    updated_at timestamptz DEFAULT now() 
);

CREATE TABLE public.entertainment_sessions ( 
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(), 
    shop_id text, 
    local_id integer, 
    asset_id uuid, 
    customer_name text, 
    started_at timestamptz, 
    ended_at timestamptz, 
    billing_type text DEFAULT 'hourly' CHECK (billing_type = ANY (ARRAY['hourly','flat'])), 
    rate numeric DEFAULT 0, 
    total_amount numeric DEFAULT 0, 
    status text DEFAULT 'active' CHECK (status = ANY (ARRAY['active','completed','cancelled'])), 
    notes text, 
    created_at timestamptz DEFAULT now() 
);
CREATE TABLE public.shops ( 
    id text PRIMARY KEY, 
    name text NOT NULL, 
    password_hash text NOT NULL, 
    owner_device_id text NOT NULL, 
    subscription_tier text DEFAULT 'FREE' CHECK (subscription_tier = ANY (ARRAY['FREE','PRO','ENTERPRISE','PRO Yearly','ENTERPRISE Yearly'])), 
    subscription_status text DEFAULT 'ACTIVE' CHECK (subscription_status = ANY (ARRAY['ACTIVE','SUSPENDED','CANCELLED'])), 
    joined_at timestamptz DEFAULT now(), 
    trial_ends_at timestamptz, 
    created_at timestamptz DEFAULT now(), 
    updated_at timestamptz DEFAULT now(), 
    admin_password_hash text, 
    owner_id uuid REFERENCES auth.users(id) ON DELETE CASCADE, 
    chain_id uuid, 
    contact_phone text, 
    trust_score integer DEFAULT 0, 
    tier text DEFAULT 'NEW', 
    branding jsonb DEFAULT '{}'::jsonb, 
    region text, 
    franchise_id text, 
    currency text DEFAULT 'KES', 
    enabled_modules text[] DEFAULT ARRAY['retail']::text[], 
    shop_type text DEFAULT 'retail' 
); 
CREATE INDEX IF NOT EXISTS idx_shops_owner_device ON public.shops(owner_device_id);

CREATE TABLE public.shop_members ( 
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    shop_id text REFERENCES public.shops(id) ON DELETE CASCADE, 
    device_id text NOT NULL, 
    user_name text NOT NULL, 
    role text DEFAULT 'STAFF' CHECK (role = ANY (ARRAY['OWNER','ADMIN','MANAGER','STAFF','CASHIER','STOCKER','INVENTORY_CLERK','SHIFT_SUPERVISOR','SUPERVISOR','INVENTORY_MANAGER','CUSTOM'])), 
    permissions jsonb DEFAULT '{}'::jsonb, 
    joined_at timestamptz DEFAULT now(), 
    last_active_at timestamptz, 
    is_active boolean DEFAULT true, 
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE, 
    phone_number text, 
    UNIQUE (shop_id, device_id) 
); 
CREATE INDEX IF NOT EXISTS idx_shop_members_shop ON public.shop_members(shop_id); 
CREATE INDEX IF NOT EXISTS idx_shop_members_device ON public.shop_members(device_id); 
CREATE INDEX IF NOT EXISTS idx_shop_members_active ON public.shop_members(shop_id, is_active);

-- 3. THE EVENT SOURCING LEDGER (SYNC ENGINE)
CREATE TABLE public.events ( 
    id text PRIMARY KEY, 
    event_type text NOT NULL, 
    payload jsonb NOT NULL, 
    hash text NOT NULL, 
    timestamp bigint NOT NULL, 
    shop_id text REFERENCES public.shops(id) ON DELETE CASCADE, 
    device_id text, 
    created_at timestamptz DEFAULT now(), 
    synced integer DEFAULT 1, 
    sync_attempts integer DEFAULT 0, 
    failed integer DEFAULT 0, 
    payload_raw text, 
    server_hash text 
); 
CREATE INDEX IF NOT EXISTS idx_events_shop ON public.events(shop_id); 
CREATE INDEX IF NOT EXISTS idx_events_timestamp ON public.events(timestamp); 
CREATE INDEX IF NOT EXISTS idx_events_type ON public.events(event_type); 
CREATE INDEX IF NOT EXISTS idx_events_synced ON public.events(synced, failed, timestamp); 
CREATE INDEX IF NOT EXISTS idx_events_shop_timestamp ON public.events(shop_id, timestamp);

-- 4. FINANCIAL & SYSTEM REGISTRY
CREATE TABLE public.subscriptions ( 
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(), 
    shop_id text UNIQUE REFERENCES public.shops(id) ON DELETE CASCADE, 
    modules text[] DEFAULT ARRAY['retail']::text[], 
    total_monthly_cost numeric DEFAULT 0, 
    billing_cycle_start date, 
    billing_cycle_end date, 
    payment_status text DEFAULT 'free' CHECK (payment_status = ANY (ARRAY['free','paid','pending','failed'])), 
    payment_method text, 
    created_at timestamptz DEFAULT now(), 
    plan_id text DEFAULT 'free', 
    max_modules integer DEFAULT 1 
);

CREATE TABLE public.mpesa_transactions ( 
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(), 
    shop_id text REFERENCES public.shops(id) ON DELETE CASCADE, 
    account_reference text, 
    merchant_request_id text, 
    checkout_request_id text UNIQUE, 
    result_code integer, 
    result_desc text, 
    amount numeric, 
    mpesa_receipt_number text, 
    transaction_date bigint, 
    phone_number text, 
    status text CHECK (status = ANY (ARRAY['pending','completed','failed','cancelled'])), 
    raw_response jsonb, 
    created_at timestamptz DEFAULT now() 
); 
CREATE INDEX IF NOT EXISTS mpesa_transactions_shop_idx ON public.mpesa_transactions(shop_id);

CREATE TABLE public.credit_profiles ( 
    shop_id text PRIMARY KEY REFERENCES public.shops(id) ON DELETE CASCADE, 
    score numeric DEFAULT 0, 
    status text DEFAULT 'ACTIVE', 
    last_evaluated timestamptz DEFAULT now(), 
    details jsonb DEFAULT '{}'::jsonb, 
    created_at timestamptz DEFAULT now(), 
    updated_at timestamptz DEFAULT now(), 
    subscription_tier text DEFAULT 'FREE' CHECK (subscription_tier = ANY (ARRAY['FREE','PRO','ENTERPRISE'])), 
    joined_at timestamptz DEFAULT now() 
);

-- 5. GLOBALLY SYNCED CATALOGS (Optional fallback to Edge)
CREATE TABLE public.inventory ( 
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    name text, 
    category text, 
    "sellingPrice" double precision, 
    "originalPrice" double precision, 
    stock integer DEFAULT 0, 
    imagePath text, 
    visual_vector text, 
    specification text, 
    barcode text, 
    created_at timestamptz DEFAULT now(), 
    updated_at timestamptz DEFAULT now(), 
    shop_id text REFERENCES public.shops(id) ON DELETE CASCADE, 
    variationsjson text, 
    is_published boolean DEFAULT false 
); 
CREATE INDEX IF NOT EXISTS inventory_shop_idx ON public.inventory(shop_id);

CREATE TABLE public.global_product_vectors ( 
    id bigint PRIMARY KEY DEFAULT nextval('global_product_vectors_id_seq'::regclass), 
    product_name text, 
    category text, 
    barcode text, 
    vector text, 
    contributed_by text, 
    shop_id text REFERENCES public.shops(id) ON DELETE CASCADE, 
    contribution_count integer DEFAULT 1, 
    last_updated timestamptz DEFAULT now(), 
    created_at timestamptz DEFAULT now() 
);

-- =========================================================
-- END EXPORT
-- Execute this file in your Supabase SQL Editor.
-- =========================================================
